### ISSUE TITLE
jenkins_plugin task no longer supports params option

### ISSUE THREAD

**Issue by marksutherland** [geerlingguy/ansible-role-jenkins#199]
Ansible 2.5 made some changes to the jenkins_plugin task which prevents plugins from being installed.

```
03:22:41 TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
03:22:42 failed: [test] (item=job-dsl) => {"changed": false, "item": "job-dsl", "msg": "The params option to jenkins_plugin was removed in Ansible 2.5since it circumvents Ansible's option handling"}
```

**Comment by marksutherland** [comment]
There's a link to this discussion in `jenkins_plugin.py`: https://meetbot.fedoraproject.org/ansible-meeting/2017-09-28/ansible_dev_meeting.2017-09-28-15.00.log.html

Looks like the fix is just to replace `params` with `args`.

Somebody also seems to have reported this in #164 .

**Comment by geerlingguy** [comment]
Thanks for opening this! I'm running into this now as well. Do you know if the change is backwards-compatible with 2.4? I haven't tested yet... but it would be really annoying to have to maybe maintain two versions of the role while people upgrade to 2.5 :/

**Comment by geerlingguy** [comment]
Thanks for the issue report and PR! This is fixed in 3.3.0.

**Comment by gilesw** [comment]
This change has broken the module. Params was used to circumvent the modules fixed parameter list I suspect.

http://docs.ansible.com/ansible/latest/modules/jenkins_plugin_module.html

Doesn't have a url_token when it's used as a parameter directly and an error is thrown. I /think/ tokens are just used as basic auth passwords a la:-

curl 'http://admin:token@JENKINS_URL:8080/

So possibly the following is just required:-

`- name: Install Jenkins plugins using token.
  jenkins_plugin:
    name: "{{ item }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_token }}"
    updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
  with_items: "{{ jenkins_plugins }}"
  when: jenkins_admin_token != ""`

This highlights a gap in the test plan. I think you can setup a 2 stage install test though and grab the token programmatically:-

https://stackoverflow.com/questions/36633725/generate-jenkins-api-token-using-rest-api

then feed that back in.

**Comment by vitas** [comment]
it still does not work, the same issue - plugins are not installed but script went through

**Comment by marksutherland** [comment]
This fixed the issue for me, but I don't use the token method like @gilesw . Is that what you are using, or are you just using the password method?

**Comment by nickbroon** [comment]
I'm hitting the following issue:
```
failed: [jenkins-dev] (item=job-dsl) => {"changed": false, "item": "job-dsl", "msg": "Unsupported parameters for (jenkins_plugin) module: url_token Supported parameters include: attributes, backup, client_cert, client_key, content, delimiter, directory_mode, follow, force, force_basic_auth, group, http_agent, jenkins_home, mode, name, owner, params, regexp, remote_src, selevel, serole, setype, seuser, src, state, timeout, unsafe_writes, updates_expiration, updates_url, url, url_password, url_username, use_proxy, validate_certs, version, with_dependencies"}
```

I have the following variables set:

```
jenkins_plugins:
  - job-dsl
  - credentials
  - git
  - workflow-aggregator

jenkins_plugin_timeout: 120
jenkins_admin_user: foo
jenkins_admin_pasword: bar
jenkins_admin_token: 12345678901234567890
```

**Comment by geerlingguy** [comment]
Please see: https://github.com/geerlingguy/ansible-role-jenkins/issues/205

I don't currently use the token method, so I don't know how much I can help there...
